
logging:
  level:
    org.springframework.web: ERROR
    name.tomedds: DEBUG

spring.main.web-application-type: NONE

# define application-specific properties
# minFileSize - ignore files smaller than this size (Kb)

dupfilefinder.minFileSize: 5

